

# This file was *autogenerated* from the file /Users/catgpt/Documents/pomerance_data_and_stats/src/core/difficulty_parameter_b.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100)
import csv
import os
import sys

def calculate_class_numbers(input_path, output_path):
    if not os.path.exists(input_path):
        print(f"[Error] Temporary staging file not found at: {input_path}")
        sys.exit(_sage_const_1 )

    with open(input_path, 'r', encoding='utf-8') as infile,          open(output_path, 'w', newline='', encoding='utf-8') as outfile:

        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        # Parse and process header block safely
        header = next(reader, None)
        if header:
            if "class_number" not in header:
                header.append("class_number")
            writer.writerow(header)

        count = _sage_const_0 
        for row in reader:
            if not row:
                continue

            try:
                # Index coordinates mapped across column definitions:
                # row[0]=prime, row[1]=A, row[2]=x0, row[3]=trials, row[4]=param_a_count
                p = int(row[_sage_const_0 ])
                A = int(row[_sage_const_1 ])
                x0 = int(row[_sage_const_2 ])
            except ValueError:
                # Safe pass-through fallback for anomalous rows
                writer.writerow(row)
                continue

            try:
                # Construct base Montgomery elliptic model curve surface
                E_base = EllipticCurve(GF(p), [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])

                # Check if x0 maps to a valid point on the curve or its quadratic twist
                rhs = (x0 ** _sage_const_3  + A * x0 ** _sage_const_2  + x0) % p
                if kronecker(rhs, p) >= _sage_const_0 :
                    E = E_base
                else:
                    E = E_base.quadratic_twist()

                t = E.trace_of_frobenius()
                D = t ** _sage_const_2  - _sage_const_4  * p

                # Directly compute the Class Number of the imaginary quadratic field using PARI
                h = pari(D).qfbclassno()

                row.append(str(int(h)))
                writer.writerow(row)

                count += _sage_const_1 
                if count % _sage_const_100  == _sage_const_0 :
                    print(f"  [Sage] Processed {count} records...")

            except Exception as e:
                row.append("ERROR")
                writer.writerow(row)
                print(f"  [Sage] Error when processing p={p}, A={A}: {e}")

    print(f"  [Sage] Subprocess completed successfully. Injected {count} class numbers.")

if __name__ == "__main__":
    if len(sys.argv) < _sage_const_3 :
        print("[Error] Missing command-line parameters for Sage runtime engine.")
        sys.exit(_sage_const_1 )
    calculate_class_numbers(sys.argv[_sage_const_1 ], sys.argv[_sage_const_2 ])

