

# This file was *autogenerated* from the file difficulty_parameter_b.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_100 = Integer(100)
import csv
import os
import sys


def get_absolute_path(relative_path_from_script):
    script_dir = os.path.dirname(os.path.abspath(__file__ if '__file__' in locals() else '.'))
    return os.path.normpath(os.path.join(script_dir, relative_path_from_script))


def calculate_class_numbers(input_path, output_path):

    if not os.path.exists(input_path):
        print(f"[Error] Input file not found, please make sure it exists at: {os.path.abspath(input_path)}")
        return

    print(f"Starting to read the file: {input_path}")

    with open(input_path, 'r', encoding='utf-8') as infile,          open(output_path, 'w', newline='', encoding='utf-8') as outfile:

        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        count = _sage_const_0 

        for row in reader:
            if not row:
                continue

            try:
                p = int(row[_sage_const_0 ])
                A = int(row[_sage_const_1 ])
                x0 = int(row[_sage_const_2 ])
            except ValueError:
                if "class_number" not in row:
                    row.append("class_number")
                writer.writerow(row)
                continue

            try:
                E_base = EllipticCurve(GF(p), [_sage_const_0 , A, _sage_const_0 , _sage_const_1 , _sage_const_0 ])

                rhs = (x0 ** _sage_const_3  + A * x0 ** _sage_const_2  + x0) % p
                if kronecker(rhs, p) >= _sage_const_0 :
                    E = E_base
                else:
                    E = E_base.quadratic_twist()

                t = E.trace_of_frobenius()
                D = t ** _sage_const_2  - _sage_const_4  * p

                h = pari(D).qfbclassno()

                row.append(str(int(h)))
                writer.writerow(row)

                count += _sage_const_1 
                if count % _sage_const_100  == _sage_const_0 :
                    print(f"Processed {count} records...")

            except Exception as e:
                row.append("ERROR")
                writer.writerow(row)
                print(f"Error when processing p={p}, A={A}: {e}")

    print(f"[Success] Processing complete. Total amount: {count} triples.")
    print(f"Results have been safely saved to: {output_path}")

if __name__ == "__main__":
     calculate_class_numbers(sys.argv[_sage_const_1 ], sys.argv[_sage_const_2 ])

